CREATE TABLE IF NOT EXISTS usuario (
                                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       nome VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    senha VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    data_nascimento VARCHAR(10),
    tipo VARCHAR(10) NOT NULL,
    foto_url VARCHAR(500),
    anos_experiencia INT,
    modalidade VARCHAR(20),
    especialidade VARCHAR(120),
    descricao VARCHAR(1000)
    );

CREATE TABLE IF NOT EXISTS plano (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     personal_id INT NOT NULL,
                                     titulo VARCHAR(120) NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    nivel VARCHAR(20) NOT NULL,
    duracao_semanas INT NOT NULL,
    objetivo VARCHAR(200),
    descricao VARCHAR(1000),
    FOREIGN KEY (personal_id) REFERENCES usuario(id)
    );

CREATE TABLE IF NOT EXISTS treino (
                                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      plano_id INT NOT NULL,
                                      nome VARCHAR(120) NOT NULL,
    dia_semana VARCHAR(20),
    exercicios VARCHAR(2000) NOT NULL,
    observacoes VARCHAR(500),
    FOREIGN KEY (plano_id) REFERENCES plano(id)
    );

CREATE TABLE IF NOT EXISTS contratacao (
                                           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           aluno_id INT NOT NULL,
                                           personal_id INT NOT NULL,
                                           data_inicio VARCHAR(10) NOT NULL,
    FOREIGN KEY (aluno_id) REFERENCES usuario(id),
    FOREIGN KEY (personal_id) REFERENCES usuario(id)
    );

CREATE TABLE IF NOT EXISTS avaliacao (
                                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         aluno_id INT NOT NULL,
                                         plano_id INT NOT NULL,
                                         estrelas INT NOT NULL,
                                         FOREIGN KEY (aluno_id) REFERENCES usuario(id),
    FOREIGN KEY (plano_id) REFERENCES plano(id)
    );